<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>KeepAwake</RootNamespace>
    <AssemblyName>KeepAwake</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <ApplicationIcon>KImages\Coffee.ico</ApplicationIcon>
    <PackageIcon>espresso_svg_hi.png</PackageIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="KImages\Coffee.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="KeepAwakeAbout.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="KeepAwakeMainForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="KeepAwakeConfigurationForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <EmbeddedResource Update="KeepAwakeAbout.resx">
      <DependentUpon>KeepAwakeAbout.cs</DependentUpon>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="KeepAwakeMainForm.resx">
      <DependentUpon>KeepAwakeMainForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="KeepAwakeConfigurationForm.resx">
      <DependentUpon>KeepAwakeConfigurationForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <Compile Update="Properties\Resources.Designer.cs">
      <AutoGen>true</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
      <DesignTime>true</DesignTime>
    </Compile>
    <None Update="KImages\espresso_svg_hi.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="KImages\espresso_svg_med.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="MSCoffee.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>true</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>true</DesignTimeSharedInput>
    </Compile>
  </ItemGroup>
</Project>